version: '3.8'

services:
    dev:
        command:
            - yarn
            - dev
        image: 'node:14.16'
        ports:
            - 3000:3000
        user: ${USER_ID:-0}:${GROUP_ID:-0}
        volumes:
            - .:/wd
            - /usr/local/share/.cache/yarn/v6
        working_dir: /wd